from pathlib import Path
import json

F=[
{"id":"three-phase-power","cat":"Power System","title":"Three-Phase Power","icon":"Tower","desc":"Calculate real active power in a balanced three-phase system.","inputs":[["Line Voltage","V","V"],["Line Current","I","A"],["Power Factor","PF",""]],"formula":"P = √3 × V × I × PF","origin":"Balanced three-phase power relationship from polyphase AC theory; not attributable to one single inventor.","derivation":"For a balanced system, total real power equals three times phase power. Using line quantities gives P = √3VI cosφ.","calc":"Math.sqrt(3)*v[0]*v[1]*v[2]","unit":"W"},
{"id":"three-phase-current","cat":"AC/DC Circuits","title":"Three-Phase Current","icon":"Wave","desc":"Find line current from kW, voltage, PF and efficiency.","inputs":[["Power","P","kW"],["Line Voltage","V","V"],["Power Factor","PF",""] ,["Efficiency","η","%"]],"formula":"I = P / (√3 × V × PF × η)","origin":"Derived from balanced three-phase power theory.","derivation":"Rearrange P = √3VIPFη for current and convert kW to W.","calc":"v[0]*1000/(Math.sqrt(3)*v[1]*v[2]*(v[3]/100))","unit":"A"},
{"id":"ohms-law","cat":"Basic Electrical","title":"Ohm's Law","icon":"Bolt","desc":"Calculate voltage from current and resistance.","inputs":[["Current","I","A"],["Resistance","R","Ω"]],"formula":"V = I × R","origin":"Associated with Georg Simon Ohm; published in 1827.","derivation":"For an ohmic conductor under stable conditions, voltage is proportional to current: V = IR.","calc":"v[0]*v[1]","unit":"V"},
{"id":"single-phase-current","cat":"AC/DC Circuits","title":"Single-Phase Current","icon":"Wave","desc":"Find AC current from real power, voltage, PF and efficiency.","inputs":[["Power","P","kW"],["Voltage","V","V"],["Power Factor","PF",""] ,["Efficiency","η","%"]],"formula":"I = P / (V × PF × η)","origin":"Derived from single-phase AC power relationship.","derivation":"Rearrange P = VIPFη for current.","calc":"v[0]*1000/(v[1]*v[2]*(v[3]/100))","unit":"A"},
{"id":"transformer-current","cat":"Transformers","title":"Transformer Full-Load Current","icon":"Transformer","desc":"Calculate transformer line current from MVA and kV.","inputs":[["Transformer Rating","S","MVA"],["Voltage","V","kV"]],"formula":"I = S / (√3 × V)","origin":"Derived from three-phase apparent power relationship.","derivation":"Use S = √3VI with consistent MVA/kV units.","calc":"v[0]*1000000/(Math.sqrt(3)*v[1]*1000)","unit":"A"},
{"id":"transformer-fault","cat":"Protection & Faults","title":"Transformer Fault Current","icon":"Shield","desc":"Estimate symmetrical fault current from transformer impedance.","inputs":[["Transformer Rating","S","MVA"],["Voltage","V","kV"],["Impedance","Z","%"]],"formula":"Isc = Irated × 100 / Z%","origin":"Based on transformer percentage impedance / per-unit principles.","derivation":"First calculate full-load current, then divide by per-unit impedance.","calc":"(v[0]*1000000/(Math.sqrt(3)*v[1]*1000))*100/v[2]","unit":"A"},
{"id":"loading","cat":"Grid / PSS / DSS","title":"Equipment Loading","icon":"Network","desc":"Calculate feeder or transformer loading percentage.","inputs":[["Actual Load","A",""] ,["Rated Load","R",""]],"formula":"Loading % = Actual / Rated × 100","origin":"Standard engineering ratio.","derivation":"Compare actual operating value to nameplate or planning rating.","calc":"v[0]/v[1]*100","unit":"%"},
{"id":"short-circuit-mva","cat":"Protection & Faults","title":"Short-Circuit MVA","icon":"Shield","desc":"Calculate fault level from kV and kA.","inputs":[["Voltage","V","kV"],["Fault Current","I","kA"]],"formula":"Ssc = √3 × kV × kA","origin":"Derived from three-phase apparent power.","derivation":"Fault level is the three-phase apparent power corresponding to fault current.","calc":"Math.sqrt(3)*v[0]*v[1]","unit":"MVA"},
{"id":"motor-speed","cat":"Motors & Drives","title":"Synchronous Speed","icon":"Motor","desc":"Calculate synchronous motor speed.","inputs":[["Frequency","f","Hz"],["Poles","P",""]],"formula":"Ns = 120f / P","origin":"Derived from rotating magnetic field theory.","derivation":"Electrical frequency and number of poles determine magnetic field rotational speed.","calc":"120*v[0]/v[1]","unit":"rpm"},
{"id":"motor-torque","cat":"Motors & Drives","title":"Motor Torque","icon":"Motor","desc":"Calculate shaft torque from kW and rpm.","inputs":[["Shaft Power","P","kW"],["Speed","n","rpm"]],"formula":"T = 9550 × P / n","origin":"Derived from P = Tω.","derivation":"Substitute angular speed ω = 2πn/60 and convert kW to W.","calc":"9550*v[0]/v[1]","unit":"N·m"},
{"id":"voltage-drop-3p","cat":"Cable Sizing","title":"3-Phase Voltage Drop","icon":"Cable","desc":"Calculate approximate three-phase cable voltage drop.","inputs":[["Current","I","A"],["Resistance/km","R","Ω/km"],["Reactance/km","X","Ω/km"],["Length","L","km"],["Power Factor","PF",""]],"formula":"ΔV = √3 I (R cosφ + X sinφ) L","origin":"Derived from AC feeder impedance and phasor relationships.","derivation":"Resolve cable impedance into in-phase and quadrature voltage-drop components.","calc":"Math.sqrt(3)*v[0]*(v[1]*v[4]+v[2]*Math.sqrt(1-v[4]*v[4]))*v[3]","unit":"V"},
{"id":"four-twenty","cat":"Measurements","title":"4–20 mA Scaling","icon":"Gauge","desc":"Convert loop current to engineering units.","inputs":[["Loop Current","I","mA"],["Lower Range","LRV",""] ,["Upper Range","URV",""]],"formula":"PV = LRV + (I−4)/16 × (URV−LRV)","origin":"Standard industrial 4–20 mA linear scaling.","derivation":"Map 4 mA to 0% span and 20 mA to 100% span.","calc":"v[1]+(v[0]-4)/16*(v[2]-v[1])","unit":"EU"},
{"id":"battery-backup","cat":"Electrician Tools","title":"Battery Backup Time","icon":"Tools","desc":"Estimate backup duration from battery energy and load.","inputs":[["Capacity","C","Ah"],["Voltage","V","V"],["Usable Efficiency","η","%"],["Load","P","W"]],"formula":"Hours = Ah × V × η / W","origin":"Energy balance relationship.","derivation":"Battery watt-hours times usable efficiency divided by load watts gives approximate hours.","calc":"v[0]*v[1]*(v[2]/100)/v[3]","unit":"h"},
{"id":"pf-correction","cat":"Power System","title":"Power Factor Correction","icon":"Tower","desc":"Calculate capacitor kVAR needed to improve PF.","inputs":[["Real Power","P","kW"],["Existing PF","PF1",""] ,["Target PF","PF2",""]],"formula":"Qc = P(tanφ1 − tanφ2)","origin":"Derived from the AC power triangle.","derivation":"Reactive power is P tanφ; the capacitor supplies the difference between existing and target reactive power.","calc":"v[0]*(Math.tan(Math.acos(v[1]))-Math.tan(Math.acos(v[2])))","unit":"kVAR"},
{"id":"saidi","cat":"Grid / PSS / DSS","title":"SAIDI","icon":"Network","desc":"System Average Interruption Duration Index.","inputs":[["Total Customer Interruption Minutes","M","min"],["Total Customers Served","N",""]],"formula":"SAIDI = Σ customer interruption duration / customers served","origin":"Utility reliability index used internationally.","derivation":"Aggregate customer interruption minutes are normalized by customer population.","calc":"v[0]/v[1]","unit":"min/customer"},
{"id":"saifi","cat":"Grid / PSS / DSS","title":"SAIFI","icon":"Network","desc":"System Average Interruption Frequency Index.","inputs":[["Total Customer Interruptions","CI",""] ,["Total Customers Served","N",""]],"formula":"SAIFI = Σ customer interruptions / customers served","origin":"Utility reliability index used internationally.","derivation":"Normalize interruption count by customer population.","calc":"v[0]/v[1]","unit":"interruptions/customer"},
{"id":"ct-secondary","cat":"Measurements","title":"CT Secondary Current","icon":"Gauge","desc":"Calculate CT secondary current from primary current and ratio.","inputs":[["Primary Current","Ip","A"],["CT Primary Rating","CTRp","A"],["CT Secondary Rating","CTRs","A"]],"formula":"Is = Ip × CTRs / CTRp","origin":"Current transformer ratio relationship.","derivation":"Secondary current scales directly according to the CT turns/current ratio.","calc":"v[0]*v[2]/v[1]","unit":"A"},
{"id":"kw-amp-3p","cat":"Electrician Tools","title":"kW to Amp — 3 Phase","icon":"Tools","desc":"Fast field conversion from kW to line current.","inputs":[["Power","P","kW"],["Voltage","V","V"],["Power Factor","PF",""]],"formula":"I = P / (√3VPF)","origin":"Derived from three-phase real power relationship.","derivation":"Rearrange P = √3VIPF and convert kW to W.","calc":"v[0]*1000/(Math.sqrt(3)*v[1]*v[2])","unit":"A"},
{"id":"unit-hp-kw","cat":"Unit Conversion","title":"HP to kW","icon":"Swap","desc":"Convert mechanical horsepower to kilowatts.","inputs":[["Horsepower","HP","hp"]],"formula":"kW = HP × 0.7457","origin":"Unit conversion using mechanical horsepower definition.","derivation":"1 mechanical horsepower ≈ 745.7 W.","calc":"v[0]*0.7457","unit":"kW"}
]
Path('eemc-react/src/formulas.generated.js').parent.mkdir(parents=True, exist_ok=True)
Path('eemc-react/src/formulas.generated.js').write_text('export const FORMULAS='+json.dumps(F,ensure_ascii=False)+';\n',encoding='utf-8')
print(f'Generated {len(F)} formulas')
