package com.jeyaraj.eemc;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.*;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import java.io.*;
import java.util.*;

public class FormulaLibraryActivity extends Activity {
    static class F {String c,n,f; F(String c,String n,String f){this.c=c;this.n=n;this.f=f;}}
    final ArrayList<F> all=new ArrayList<>();
    final LinkedHashMap<String,ArrayList<F>> byCat=new LinkedHashMap<>();
    LinearLayout page; ScrollView scroll; String mode="Learning"; F selected;
    final int NAVY=Color.rgb(8,63,102), BLUE=Color.rgb(24,116,218), ORANGE=Color.rgb(255,137,31), GREEN=Color.rgb(34,180,105), BG=Color.rgb(244,248,252), TEXT=Color.rgb(18,54,83), MUTED=Color.rgb(91,111,130);
    final int[] CATCOL={Color.rgb(255,184,32),Color.rgb(52,159,224),Color.rgb(244,126,42),Color.rgb(32,168,164),Color.rgb(226,79,82),Color.rgb(122,83,214),Color.rgb(73,177,84),Color.rgb(218,128,38),Color.rgb(142,91,46),Color.rgb(31,120,204),Color.rgb(87,132,163),Color.rgb(235,92,142),Color.rgb(44,153,133),Color.rgb(113,89,191),Color.rgb(226,169,39),Color.rgb(80,108,128),Color.rgb(64,135,104),Color.rgb(100,112,128),Color.rgb(97,77,173),Color.rgb(44,128,175)};
    Uri pendingPdf;

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);load();showHome();}

    void load(){try{String[] files=getAssets().list("formulas");if(files==null)return;Arrays.sort(files);for(String fn:files){BufferedReader r=new BufferedReader(new InputStreamReader(getAssets().open("formulas/"+fn)));String s;while((s=r.readLine())!=null){String[] p=s.split("\\|",3);if(p.length==3){F x=new F(p[0],p[1],p[2]);all.add(x);if(!byCat.containsKey(x.c))byCat.put(x.c,new ArrayList<>());byCat.get(x.c).add(x);}}r.close();}}catch(Exception e){Toast.makeText(this,"Formula library load error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}

    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    TextView tv(String s,float sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(12,10,12,10);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    LinearLayout card(int color,int p,float r){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(p,p,p,p);l.setBackground(bg(color,r));return l;}
    void base(){scroll=new ScrollView(this);scroll.setFillViewport(true);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(18,0,18,32);page.setBackgroundColor(BG);scroll.addView(page);setContentView(scroll);}
    void gap(int h){Space s=new Space(this);page.addView(s,new LinearLayout.LayoutParams(1,h));}

    void showHome(){base();
        LinearLayout head=card(NAVY,18,0);LinearLayout hrow=new LinearLayout(this);hrow.setGravity(Gravity.CENTER_VERTICAL);
        TextView logo=tv("⚡\nEEMC",18,Color.WHITE,true);logo.setGravity(Gravity.CENTER);logo.setBackground(bg(ORANGE,80));hrow.addView(logo,new LinearLayout.LayoutParams(88,88));
        LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(14,0,0,0);ht.addView(tv("Electrical Engineer\nMaster Calculator",25,Color.WHITE,true));ht.addView(tv("Formula Library • Developed by Jeyaraj",14,Color.rgb(213,231,246),false));hrow.addView(ht,new LinearLayout.LayoutParams(0,-2,1));head.addView(hrow);page.addView(head);gap(14);

        LinearLayout hero=card(Color.WHITE,18,26);hero.addView(tv("172 Electrical Engineering Formulas",27,TEXT,true));hero.addView(tv("20 categories • Offline • Formula origin • Deep derivation • PDF export",15,MUTED,false));TextView stat=tv("Quick Mode = answer/formula\nEngineer Mode = formula + symbols + engineering notes\nLearning Mode = deeper derivation + origin + worked guidance",16,NAVY,true);hero.addView(stat);page.addView(hero);gap(12);

        EditText search=new EditText(this);search.setSingleLine(true);search.setHint("Search formula, transformer, fault, motor, SAIDI...");search.setTextSize(16);search.setPadding(22,4,22,4);search.setBackground(bg(Color.WHITE,32));search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);page.addView(search,new LinearLayout.LayoutParams(-1,64));search.setOnEditorActionListener((v,id,e)->{search(v.getText().toString());return true;});gap(10);

        page.addView(tv("Mode",20,TEXT,true));LinearLayout mr=new LinearLayout(this);String[] ms={"Quick","Engineer","Learning"};int[] mc={GREEN,BLUE,ORANGE};for(int i=0;i<3;i++){final String m=ms[i];Button b=new Button(this);b.setText(m);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackground(bg(mc[i],22));b.setOnClickListener(v->{mode=m;Toast.makeText(this,m+" Mode selected",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,58,1);lp.setMargins(4,2,4,2);mr.addView(b,lp);}page.addView(mr);gap(12);

        LinearLayout actions=new LinearLayout(this);Button calc=new Button(this);calc.setText("Open Interactive Calculators");calc.setAllCaps(false);calc.setTextColor(Color.WHITE);calc.setTextSize(16);calc.setBackground(bg(BLUE,22));calc.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));actions.addView(calc,new LinearLayout.LayoutParams(0,58,1));page.addView(actions);gap(16);

        page.addView(tv("Formula Categories",23,TEXT,true));
        ArrayList<String> cats=new ArrayList<>(byCat.keySet());for(int r=0;r<(cats.size()+1)/2;r++){LinearLayout row=new LinearLayout(this);for(int c=0;c<2;c++){int idx=r*2+c;if(idx>=cats.size()){row.addView(new Space(this),new LinearLayout.LayoutParams(0,1,1));continue;}String name=cats.get(idx);ArrayList<F> list=byCat.get(name);LinearLayout cc=card(CATCOL[idx%CATCOL.length],12,24);TextView a=tv(name,17,Color.WHITE,true);TextView n=tv(list.size()+" formulas",13,Color.WHITE,false);cc.addView(a);cc.addView(n);cc.setOnClickListener(v->showCategory(name));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,102,1);lp.setMargins(5,5,5,5);row.addView(cc,lp);}page.addView(row);}gap(16);
        TextView foot=tv("For engineering design, protection settings, earthing, cable selection and safety decisions, verify the applicable IEC/IEEE/local standard and manufacturer data in addition to the calculated result.",13,MUTED,false);foot.setGravity(Gravity.CENTER);page.addView(foot);
    }

    void search(String q){if(q==null||q.trim().isEmpty()){showAll();return;}String z=q.toLowerCase(Locale.US);ArrayList<F> r=new ArrayList<>();for(F x:all)if(x.n.toLowerCase(Locale.US).contains(z)||x.c.toLowerCase(Locale.US).contains(z)||x.f.toLowerCase(Locale.US).contains(z))r.add(x);showFormulaList("Search results ("+r.size()+")",r);}
    void showAll(){showFormulaList("All formulas",all);}
    void showCategory(String c){showFormulaList(c+" ("+byCat.get(c).size()+")",byCat.get(c));}
    void showFormulaList(String title,List<F> list){String[] a=new String[list.size()];for(int i=0;i<a.length;i++)a[i]=list.get(i).n+"\n"+list.get(i).f;new AlertDialog.Builder(this).setTitle(title).setItems(a,(d,w)->showDetail(list.get(w))).setNegativeButton("Close",null).show();}

    void showDetail(F x){selected=x;base();
        LinearLayout top=card(NAVY,12,0);LinearLayout tr=new LinearLayout(this);tr.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",38,Color.WHITE,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->showHome());tr.addView(back,new LinearLayout.LayoutParams(54,58));tr.addView(tv(x.n,21,Color.WHITE,true),new LinearLayout.LayoutParams(0,58,1));top.addView(tr);page.addView(top);gap(12);
        LinearLayout tag=card(Color.WHITE,16,22);tag.addView(tv(x.c,15,BLUE,true));tag.addView(tv(x.n,26,TEXT,true));page.addView(tag);gap(10);
        section("FORMULA",x.f,Color.rgb(230,242,255));
        if(!mode.equals("Quick")){section("SYMBOLS & UNITS",symbols(x),Color.WHITE);section("ENGINEERING MEANING",meaning(x),Color.WHITE);}
        if(mode.equals("Learning")){section("DEEPER DERIVATION",derivation(x),Color.rgb(255,247,231));section("FORMULA ORIGIN / HISTORY",origin(x),Color.rgb(241,236,255));section("WORKED-EXAMPLE METHOD",example(x),Color.WHITE);}
        LinearLayout wr=card(Color.WHITE,12,20);Button pdf=new Button(this);pdf.setText("Download Explanation as PDF");pdf.setAllCaps(false);pdf.setTextSize(16);pdf.setTextColor(Color.WHITE);pdf.setBackground(bg(ORANGE,22));pdf.setOnClickListener(v->requestPdf(x));wr.addView(pdf);Button calc=new Button(this);calc.setText("Open Interactive Calculators");calc.setAllCaps(false);calc.setTextSize(15);calc.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));wr.addView(calc);page.addView(wr);gap(10);
        section("IMPORTANT", "This app gives engineering calculations and learning explanations. Equipment selection, protection grading, cable ampacity, earthing and fault-duty decisions must also follow the applicable standard, installation conditions, manufacturer data and utility requirements.",Color.rgb(255,235,235));
    }
    void section(String h,String body,int color){LinearLayout c=card(color,16,22);c.addView(tv(h,15,NAVY,true));TextView b=tv(body,16,TEXT,false);b.setLineSpacing(4,1.06f);c.addView(b);page.addView(c);gap(9);}

    String symbols(F x){return "Read every symbol directly from the equation and keep one consistent unit system. Convert kW↔W, kV↔V, MVA↔VA, kA↔A and percent↔decimal when required. √3 = 1.7320508 for balanced three-phase line relationships. Always confirm whether voltage/current values are line or phase quantities.";}
    String meaning(F x){return categoryMeaning(x.c)+"\n\nPractical check: confirm rated values, actual operating data, power factor sign, efficiency, phase convention, conductor length basis, and whether the study needs minimum or maximum operating conditions.";}
    String categoryMeaning(String c){if(c.contains("Protection"))return "Used in fault-level and relay-protection studies. Relay curves, CT performance and coordination margins must match the actual relay and system.";if(c.contains("Cable"))return "Used to estimate conductor voltage drop, losses and thermal withstand. Final cable size also depends on ampacity, installation, ambient temperature, grouping and standard limits.";if(c.contains("Grid"))return "Used in feeder, transformer and substation operation to assess loading, spare capacity, transfers and voltage condition.";if(c.contains("SCADA"))return "Used to convert instrumentation and RTU raw signals into engineering values and back.";if(c.contains("Earthing"))return "Used for grounding studies. Touch/step limits and grid design require the applicable safety standard and soil/fault-current data.";return "A standard electrical-engineering relationship used for analysis, design, commissioning, operation or troubleshooting.";}
    String derivation(F x){String n=x.n;
        if(n.contains("Ohm"))return "For an ohmic conductor at constant physical conditions, measured voltage is proportional to current. The proportionality constant is resistance R. Therefore V ∝ I and V = RI. Algebraically isolating the required variable gives I = V/R or R = V/I.";
        if(n.equals("Three Phase Real Power"))return "1) Per-phase real power is Pφ = Vφ Iφ cosφ.\n2) Total balanced three-phase power is P = 3Pφ.\n3) For star, Vφ = VL/√3 and Iφ = IL.\n4) Substitute: P = 3(VL/√3)ILcosφ = √3 VL IL cosφ.\n5) The same final line-power equation results for a balanced delta system.";
        if(n.contains("Full Load Current 3φ")||n.equals("Generator Current"))return "Start with balanced three-phase apparent power S = √3 VL IL. Solve algebraically for line current: IL = S/(√3 VL). Keep S and V in compatible units; e.g. kVA with volts requires ×1000.";
        if(n.contains("Fault Current from Z%")||n.contains("Transformer Secondary Fault"))return "Percent impedance is the percentage of rated voltage required to circulate rated current with the transformer output shorted. If upstream source impedance is neglected, applying 100% rated voltage increases current in inverse proportion to Z%: Isc ≈ Irated × 100/Z%. This is a first-pass symmetrical estimate; formal studies should include the source/network impedance.";
        if(n.equals("Synchronous Speed"))return "A rotating magnetic field moves one mechanical pole-pair cycle per electrical cycle. Pole pairs = P/2, so mechanical revolutions/second = f/(P/2)=2f/P. Multiply by 60 s/min: Ns = 120f/P rpm.";
        if(n.equals("Slip"))return "Rotor speed Nr is slightly below synchronous speed Ns in normal motoring. Speed difference = Ns−Nr. Divide by Ns to normalize it and multiply by 100 for percent slip: s%=(Ns−Nr)/Ns×100.";
        if(n.contains("Voltage Drop")&&x.c.contains("Cable"))return "Represent cable impedance by R+jX. The voltage component in the direction of load current is Rcosφ+Xsinφ. Multiply by current and route length. Use factor 2 for a single-phase go-and-return circuit; use √3 for a balanced three-phase line-to-line drop.";
        if(n.contains("PF Correction"))return "Reactive power of a load is Q=P tanφ where φ=arccos(PF). Original Q1=P tanφ1 and target Q2=P tanφ2. A capacitor supplies the difference, so Qc=Q1−Q2=P(tanφ1−tanφ2).";
        if(n.equals("4-20 mA Scaling"))return "A 4–20 mA signal has a 16 mA usable span. Normalize the measured signal: fraction=(mA−4)/16. Multiply by the engineering span URV−LRV and add LRV: PV=LRV+fraction(URV−LRV).";
        if(n.equals("MAPE"))return "For each interval calculate ei=|Ai−Fi|/|Ai|. Average all ei values, then multiply by 100. MAPE is undefined where actual Ai=0, so zero-actual intervals need a defined handling rule.";
        if(n.equals("SAIDI"))return "Add customer-interruption duration across all sustained interruptions to obtain total customer interruption minutes. Divide by the total customers served. The result is average sustained interruption duration experienced per customer.";
        if(n.equals("SAIFI"))return "Add all sustained customer interruptions in the reporting period and divide by total customers served. The result is average sustained interruption frequency per customer.";
        return "1) Identify the governing electrical relationship for "+x.c+".\n2) Express all quantities in compatible units.\n3) Rearrange the governing equation to isolate the desired variable.\n4) Substitute measured/rated values.\n5) Calculate using correct order of operations.\n6) Check the result against physical limits, equipment ratings and the applicable engineering standard.\n\nDisplayed relationship: "+x.f;}
    String origin(F x){String n=x.n;if(n.contains("Ohm"))return "Associated scientist: Georg Simon Ohm. His 1827 work established the voltage-current-resistance relationship for ohmic conductors.";if(n.contains("Joule"))return "Associated scientist: James Prescott Joule; his 19th-century experiments established the electrical-heating relationship.";if(n.contains("IDMT"))return "Origin: standardized inverse-time overcurrent protection characteristics. Check the exact relay curve constants and IEC 60255 / manufacturer documentation.";if(n.equals("SAIDI")||n.equals("SAIFI")||n.equals("CAIDI")||n.equals("AENS")||n.equals("ENS"))return "Origin: electric-utility reliability indices used internationally; definitions are commonly aligned with standards/guides such as IEEE 1366 and local regulator rules.";if(x.c.equals("Transformers"))return "Origin: transformer electromagnetic theory is rooted in Faraday's law of induction and later AC engineering development; most transformer calculation equations are derived engineering relationships rather than one-person inventions.";if(x.c.equals("AC & Three Phase"))return "Origin: developed through AC and polyphase-system theory in the late 19th century. These are derived relationships, so assigning one inventor is usually misleading.";return "Origin: standard electrical-engineering relationship derived from circuit, electromagnetic, power-system, measurement or reliability theory. Where no single inventor is historically established, the app labels the technical origin instead of inventing an attribution.";}
    String example(F x){return "Example workflow:\n1) Read the equipment/nameplate or operational values.\n2) Convert them to the units required by the equation.\n3) Write the formula exactly as shown.\n4) Substitute each value with its unit.\n5) Calculate intermediate terms first, then the final answer.\n6) Perform a reasonableness check.\n\nFor common daily formulas, use the app's Interactive Calculators to get numeric substitution and step-by-step working.";}

    void requestPdf(F x){selected=x;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"EEMC_"+x.n.replaceAll("[^A-Za-z0-9]+","_")+".pdf");startActivityForResult(i,77);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==77&&res==RESULT_OK&&data!=null&&selected!=null){try{writePdf(data.getData(),selected);Toast.makeText(this,"PDF saved",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"PDF export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}}
    void writePdf(Uri uri,F x)throws Exception{PdfDocument doc=new PdfDocument();PdfDocument.PageInfo info=new PdfDocument.PageInfo.Builder(595,1300,1).create();PdfDocument.Page p=doc.startPage(info);Canvas c=p.getCanvas();Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setColor(TEXT);paint.setTextSize(17);paint.setTypeface(Typeface.DEFAULT_BOLD);float y=45;c.drawText("Electrical Engineer Master Calculator (EEMC)",36,y,paint);y+=30;paint.setTextSize(13);paint.setTypeface(Typeface.DEFAULT);c.drawText("Developed by Jeyaraj",36,y,paint);y+=38;y=drawBlock(c,paint,"CATEGORY: "+x.c+"\n\n"+x.n+"\n\nFORMULA\n"+x.f+"\n\nSYMBOLS & UNITS\n"+symbols(x)+"\n\nDERIVATION\n"+derivation(x)+"\n\nORIGIN / HISTORY\n"+origin(x)+"\n\nWORKED-EXAMPLE METHOD\n"+example(x)+"\n\nIMPORTANT\nVerify applicable standards, manufacturer data, installation conditions and safety requirements before making engineering decisions.",36,y,523);doc.finishPage(p);OutputStream o=getContentResolver().openOutputStream(uri);doc.writeTo(o);o.close();doc.close();}
    float drawBlock(Canvas c,Paint p,String s,float x,float y,float width){p.setTextSize(12.5f);p.setTypeface(Typeface.DEFAULT);String[] paras=s.split("\\n",-1);for(String para:paras){if(para.length()==0){y+=16;continue;}ArrayList<String> words=new ArrayList<>(Arrays.asList(para.split(" ")));String line="";for(String w:words){String test=line.length()==0?w:line+" "+w;if(p.measureText(test)>width){c.drawText(line,x,y,p);y+=17;line=w;}else line=test;}if(line.length()>0){c.drawText(line,x,y,p);y+=17;}}return y;}
}
